# This is a "fake" Bazel workspace file used to force Renovate to run the integration tests against
# each new release of Atom on GitHub. The versions listed below are the most recent ones that the
# integration tests have passed against. This file should not be edited manually.

workspace(name="integration_tests")

git_repository(
  name = "atom-stable",
  remote = "https://github.com/atom/atom.git",
  tag = "v1.49.0",
)

git_repository(
  name = "atom-beta",
  remote = "https://github.com/atom/atom.git",
  tag = "v1.51.0-beta0",
)
